export const indianStates = [
	'Andaman and Nicobar Islands',
	'Andhra Pradesh',
	'Arunachal Pradesh',
	'Assam',
	'Bihar',
	'Chandigarh',
	'Chhattisgarh',
	'Dadra and Nagar Haveli and Daman and Diu',
	'Delhi',
	'Goa',
	'Gujarat',
	'Haryana',
	'Himachal Pradesh',
	'Jammu and Kashmir',
	'Jharkhand',
	'Karnataka',
	'Kerala',
	'Ladakh',
	'Lakshadweep Islands',
	'Madhya Pradesh',
	'Maharashtra',
	'Manipur',
	'Meghalaya',
	'Mizoram',
	'Nagaland',
	'Odisha',
	'Other Territory',
	'Pondicherry',
	'Punjab',
	'Rajasthan',
	'Sikkim',
	'Tamil Nadu',
	'Telangana',
	'Tripura',
	'Uttar Pradesh',
	'Uttarakhand',
	'West Bengal'
];

export const vietnamCity = [
	{ value: 'Bà Rịa', parent: 'Bà Rịa – Vũng Tàu' },
	{ value: 'Bạc Liêu', parent: 'Bạc Liêu' },
	{ value: 'Bảo Lộc', parent: 'Lâm Đồng' },
	{ value: 'Bắc Giang', parent: 'Bắc Giang' },
	{ value: 'Bắc Kạn', parent: 'Bắc Kạn' },
	{ value: 'Bắc Ninh', parent: 'Bắc Ninh' },
	{ value: 'Bến Tre', parent: 'Bến Tre' },
	{ value: 'Biên Hòa', parent: 'Đồng Nai' },
	{ value: 'Buôn Ma Thuột', parent: 'Đắk Lắk' },
	{ value: 'Cần Thơ', parent: 'Cần Thơ' },
	{ value: 'Cà Mau', parent: 'Cà Mau' },
	{ value: 'Cam Ranh', parent: 'Khánh Hòa' },
	{ value: 'Cao Bằng', parent: 'Cao Bằng' },
	{ value: 'Cao Lãnh', parent: 'Đồng Tháp' },
	{ value: 'Cẩm Phả', parent: 'Quảng Ninh' },
	{ value: 'Châu Đốc', parent: 'An Giang' },
	{ value: 'Đà Nẵng', parent: 'Đà Nẵng' },
	{ value: 'Đà Lạt', parent: 'Lâm Đồng' },
	{ value: 'Điện Biên Phủ', parent: 'Điện Biên' },
	{ value: 'Đông Hà', parent: 'Quảng Trị' },
	{ value: 'Đồng Hới', parent: 'Quảng Bình' },
	{ value: 'Đồng Xoài', parent: 'Bình Phước' },
	{ value: 'Hà Nội', parent: 'Hà Nội' },
	{ value: 'Hồ Chí Minh', parent: 'Hồ Chí Minh' },
	{ value: 'Hà Giang', parent: 'Hà Giang' },
	{ value: 'Hải Phòng', parent: 'Hải Phòng' },
	{ value: 'Hạ Long', parent: 'Quảng Ninh' },
	{ value: 'Hà Tiên', parent: 'Kiên Giang' },
	{ value: 'Hà Tĩnh', parent: 'Hà Tĩnh' },
	{ value: 'Hải Dương', parent: 'Hải Dương' },
	{ value: 'Hòa Bình', parent: 'Hòa Bình' },
	{ value: 'Hội An', parent: 'Quảng Nam' },
	{ value: 'Huế', parent: 'Thừa Thiên Huế' },
	{ value: 'Hưng Yên', parent: 'Hưng Yên' },
	{ value: 'Kon Tum', parent: 'Kon Tum' },
	{ value: 'Lai Châu', parent: 'Lai Châu' },
	{ value: 'Lạng Sơn', parent: 'Lạng Sơn' },
	{ value: 'Lào Cai', parent: 'Lào Cai' },
	{ value: 'Long Xuyên', parent: 'An Giang' },
	{ value: 'Móng Cái', parent: 'Quảng Ninh' },
	{ value: 'Mỹ Tho', parent: 'Tiền Giang' },
	{ value: 'Nam Định', parent: 'Nam Định' },
	{ value: 'Nha Trang', parent: 'Khánh Hòa' },
	{ value: 'Ninh Bình', parent: 'Ninh Bình' },
	{ value: 'Phan Rang - Tháp Chàm', parent: 'Ninh Thuận' },
	{ value: 'Phan Thiết', parent: 'Bình Thuận' },
	{ value: 'Phủ Lý', parent: 'Hà Nam' },
	{ value: 'Phúc Yên', parent: 'Vĩnh Phúc' },
	{ value: 'Pleiku', parent: 'Gia Lai' },
	{ value: 'Quảng Ngãi', parent: 'Quảng Ngãi' },
	{ value: 'Quy Nhơn', parent: 'Bình Định' },
	{ value: 'Rạch Giá', parent: 'Kiên Giang' },
	{ value: 'Sa Đéc', parent: 'Đồng Tháp' },
	{ value: 'Sầm Sơn', parent: 'Thanh Hóa' },
	{ value: 'Sóc Trăng', parent: 'Sóc Trăng' },
	{ value: 'Sơn La', parent: 'Sơn La' },
	{ value: 'Sông Công', parent: 'Thái Nguyên' },
	{ value: 'Thủ Đức', parent: 'Thủ Đức' },
	{ value: 'Tam Điệp', parent: 'Ninh Bình' },
	{ value: 'Tam Kỳ', parent: 'Quảng Nam' },
	{ value: 'Tân An', parent: 'Long An' },
	{ value: 'Tây Ninh', parent: 'Tây Ninh' },
	{ value: 'Thái Bình', parent: 'Thái Bình' },
	{ value: 'Thái Nguyên', parent: 'Thái Nguyên' },
	{ value: 'Thanh Hóa', parent: 'Thanh Hóa' },
	{ value: 'Thủ Dầu Một', parent: 'Bình Dương' },
	{ value: 'Trà Vinh', parent: 'Trà Vinh' },
	{ value: 'Tuy Hòa', parent: 'Phú Yên' },
	{ value: 'Tuyên Quang', parent: 'Tuyên Quang' },
	{ value: 'Uông Bí', parent: 'Quảng Ninh' },
	{ value: 'Vị Thanh', parent: 'Hậu Giang' },
	{ value: 'Việt Trì', parent: 'Phú Thọ' },
	{ value: 'Vinh', parent: 'Nghệ An' },
	{ value: 'Vĩnh Long', parent: 'Vĩnh Long' },
	{ value: 'Vĩnh Yên', parent: 'Vĩnh Phúc' },
	{ value: 'Vũng Tàu', parent: 'Bà Rịa – Vũng Tàu' },
	{ value: 'Yên Bái', parent: 'Yên Bái' },
	{ value: 'Thuận An', parent: 'Bình Dương' },
	{ value: 'Dĩ An', parent: 'Bình Dương' },
	{ value: 'Phú Quốc', parent: 'Kiên Giang' },
	{ value: 'Ngã Bảy', parent: 'Hậu Giang' },
	{ value: 'Long Khánh', parent: 'Đồng Nai' },
	{ value: 'Hồng Ngự', parent: 'Đồng Tháp' },
	{ value: 'Gia Nghĩa', parent: 'Đắk Nông' }
];

export const vietnamStates = [
	{ value: 'An Giang', key: 1 },
	{ value: 'Bà Rịa – Vũng Tàu', key: 2 },
	{ value: 'Bạc Liêu', key: 3 },
	{ value: 'Bắc Giang', key: 4 },
	{ value: 'Bắc Kạn', key: 5 },
	{ value: 'Bắc Ninh', key: 6 },
	{ value: 'Bến Tre', key: 7 },
	{ value: 'Bình Dương', key: 8 },
	{ value: 'Bình Định', key: 9 },
	{ value: 'Bình Phước', key: 10 },
	{ value: 'Bình Thuận', key: 11 },
	{ value: 'Cà Mau', key: 12 },
	{ value: 'Cao Bằng', key: 13 },
	{ value: 'Cần Thơ', key: 14 },
	{ value: 'Đà Nẵng', key: 15 },
	{ value: 'Đắk Lắk', key: 16 },
	{ value: 'Đắk Nông', key: 17 },
	{ value: 'Điện Biên', key: 18 },
	{ value: 'Đồng Nai', key: 19 },
	{ value: 'Đồng Tháp', key: 20 },
	{ value: 'Gia Lai', key: 21 },
	{ value: 'Hà Giang', key: 22 },
	{ value: 'Hà Nam', key: 23 },
	{ value: 'Hà Nội', key: 24 },
	{ value: 'Hà Tĩnh', key: 25 },
	{ value: 'Hải Dương', key: 26 },
	{ value: 'Hải Phòng', key: 27 },
	{ value: 'Hậu Giang', key: 28 },
	{ value: 'Hòa Bình', key: 29 },
	{ value: 'Hồ Chí Minh', key: 30 },
	{ value: 'Hưng Yên', key: 31 },
	{ value: 'Khánh Hòa', key: 32 },
	{ value: 'Kiên Giang', key: 33 },
	{ value: 'Kon Tum', key: 34 },
	{ value: 'Lai Châu', key: 35 },
	{ value: 'Lạng Sơn', key: 36 },
	{ value: 'Lào Cai', key: 37 },
	{ value: 'Lâm Đồng', key: 38 },
	{ value: 'Long An', key: 39 },
	{ value: 'Nam Định', key: 40 },
	{ value: 'Nghệ An', key: 41 },
	{ value: 'Ninh Bình', key: 42 },
	{ value: 'Ninh Thuận', key: 43 },
	{ value: 'Phú Thọ', key: 44 },
	{ value: 'Phú Yên', key: 45 },
	{ value: 'Quảng Bình', key: 46 },
	{ value: 'Quảng Nam', key: 47 },
	{ value: 'Quảng Ngãi', key: 48 },
	{ value: 'Quảng Ninh', key: 49 },
	{ value: 'Quảng Trị', key: 50 },
	{ value: 'Sóc Trăng', key: 51 },
	{ value: 'Sơn La', key: 52 },
	{ value: 'Thủ Đức', key: 53 },
	{ value: 'Tây Ninh', key: 54 },
	{ value: 'Thái Bình', key: 55 },
	{ value: 'Thái Nguyên', key: 56 },
	{ value: 'Thanh Hóa', key: 57 },
	{ value: 'Thừa Thiên Huế', key: 58 },
	{ value: 'Tiền Giang', key: 59 },
	{ value: 'Trà Vinh', key: 60 },
	{ value: 'Tuyên Quang', key: 61 },
	{ value: 'Vĩnh Long', key: 62 },
	{ value: 'Vĩnh Phúc', key: 63 },
	{ value: 'Yên Bái', key: 64 }
];
